sudo: required
dist: trusty
os: linux
language: generic
services: docker
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: builds@travis-ci.org
  - TRAVIS_REPO_SLUG: jacek-jonca/diversity-newspaper
  - GIT_BRANCH: latexdocker
  - secure: ${GH_TOKEN}
script:
- "./changefile.sh"
- wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
- chmod +x latexdockercmd.sh
#- "./latexdockercmd.sh latexmk -xelatex -interaction=nonstopmode -halt-on-error diversity.tex"
- "./latexdockercmd.sh latexmk -cd -f -interaction=batchmode -pdf diversity.tex -outdir=$TRAVIS_BUILD_DIR/"
#- "./latexdockercmd.sh pdflatex diversity.tex"
# Force push the PDF to GitHub
- cd $TRAVIS_BUILD_DIR
- git checkout --orphan $TRAVIS_BRANCH-pdf
- git rm -rf .
- git add -f diversity.pdf
- git -c user.name='travis' -c user.email='travis' commit -m "building the PDF"
- git push -q -f https://jacek-jonca:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
before_deploy:
- "./deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - diversity.pdf
  skip_cleanup: true
  on:
    repo: jacek-jonca/diversity-newspaper
    tags: false
    all_branches: true
notifications:
  email: false
