sudo: required
dist: trusty
os: linux
language: generic
services: docker
env:
  global:
    - secure: https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
    - GIT_NAME: Travis CI
    - GIT_EMAIL: builds@travis-ci.org
    - TRAVIS_REPO_SLUG: jacek-jonca/diversity-newspaper
    - GIT_BRANCH: master
script:
  - ./changefile.sh
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic diversity.tex"
before_deploy:
  - ./deploy.sh
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  # add files to the release - specify them individually instead of a git add . or git add -A
    - "diversity.pdf"
  skip_cleanup: true
  on:
    repo: jacek-jonca/diversity-newspaper
    tags: false
    all_branches: true
notifications:
    email: false

    3776fad8b3403ce33d537d69d7a60d2a76af348a